### ISSUE TITLE
Not good

### ISSUE THREAD

**Issue by devkarthin** [DeadUSB/deadusb.com#1]
Get good.

**Comment by DeadUSB** [comment]
hey bitch

yeah you you bitch

not nice

i’m telling sunkissed
she will break up with you soon.

from karee

**Comment by devkarthin** [comment]
Sprryu

**Comment by devkarthin** [comment]
Bum,p


Bump

**Comment by devkarthin** [comment]
Not fixed. Re-opening...

**Comment by devkarthin** [comment]
How do i re opne What eh heck
