### ISSUE TITLE
Do u want karoom.org

### ISSUE THREAD

**Issue by devkarthin** [DeadUSB/deadusb.com#4]
I can buy it for U
No charge. I will transfr it 2 u

Thx.-Karthin

**Comment by DeadUSB** [comment]
thank you for your inquiry 

i am interested in this offer yet i wonder how will the domain be transferred?

thanks,
deadusb

**Comment by devkarthin** [comment]
Pork bun  Its cheap and pretty good.I used it for areweblogdotsppongydotcomyet.xyz

**Comment by DeadUSB** [comment]
ok i agree i will take the domain thank you

**Comment by devkarthin** [comment]
Ok. is karoom.org OK or would u like something different (any thing $15 or less is OK)👉https://porkbun.com
Search here

**Comment by DeadUSB** [comment]
ok i will look around... 

i think deadusb.com would be nicer...

**Comment by devkarthin** [comment]
Ok.Ill buy it soon.Keep in mind that I will only buy it for 1 year. If you choose not to buy more years, the domain will expire and you will lose it.

**Comment by DeadUSB** [comment]
thank you so much Karthin i will use this domain and i will use it very much well

i will renew on my Oewn thank you for your Gracefullness and your offer i thank you very very much
big appreciate...
