### ISSUE TITLE
it's actually git pull --rebase. Lol

### ISSUE THREAD

**Issue by devkarthin** [DeadUSB/deadusb.com#5]
https://github.com/DeadUSB/DeadUSB.github.io/blob/5f958024e372bbbb54390a275c14f32bb35f3a00/blog.html#L48

**Comment by DeadUSB** [comment]
there are times where i do not appreciate your comments

**Comment by devkarthin** [comment]
Ok.. Could u fix it tho?

**Comment by DeadUSB** [comment]
ok
